apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql  
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
